### PR TITLE
Microoptimizations for DefaultParameterNameProvider

### PR DESCRIPTION
**Pull request by andruskutt**

### CODE REVIEW

**Comment by graemerocher** [comment]
Can you ensure the commits are done with the same email/account as your GitHub account. They appear to be different

**Comment by andruskutt** [comment]
Initial commit was done without configuring git.
In second commit I tried this: git commit --amend --author="andruskutt <email>"
Can I do something more?

**Comment by graemerocher** [comment]
You need to do all the commits with the account you submitted the PR with otherwise we can't merge I am afraid

**Comment by andruskutt** [comment]
Ok, I will start again and closing this request

**Pull request closed without merging**
