### PR TITLE
M2

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@wetted can you investigate the failure?

**Comment by kevin-wise** [comment]
I see this test is still disabled. When I run it locally, it fails because `{org.hibernate.validator.constraints.URL.message}` is coming through unchanged.  Is there an issue written up for this (the linkes one is closed)?  I am also seeing the same thing in my service after migrating to Micronaut 4.  I have a workaround but I'm not sure why the behavior changed, so I'm not sure if it's the best way to fix. Happy to post a PR though

**Comment by kevin-wise** [comment]
https://github.com/micronaut-projects/micronaut-hibernate-validator/pull/407

**Comment by kevin-wise** [comment]
@sdelamo making sure you saw this ☝️

**Comment by kevin-wise** [comment]
I went ahead and opened https://github.com/micronaut-projects/micronaut-hibernate-validator/issues/410

**Pull request merged**
